name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.14.0"

      - name: Install packages
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to surge
        run: surge ./build jenkk.surge.sh --token ${{secrets.SURGE_TOKEN}}
