# This is a basic workflow to help you get started with Actions

name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.14.0
          
      - name: npm setup
        uses: ng-easy/npm-setup@v1.7.2
        
      - name: surge setup
        run: npm install -g surge
      
      - name: npm instal
        run: npm install
      
      - name: build
        run: npm build
  
      - name: deploy to surge
        run: surge ./build dep-git-actions.surge.sh --token=${{secrets.SURGE_TOKEN}}
